spring.datasource.url=jdbc:mysql://localhost:3306/nombre_base
spring.datasource.username=usuario_mysql
spring.datasource.password=password_mysql

spring.security.user.name=usuario
spring.security.user.password=password