# Nombre de la aplicación
spring.application.name=apirest-productos

# Configuración de base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Usuario Spring Security (solo desarrollo)
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}